spring:
  cloud:
    gateway:
      routes:
        - id: auth # 路由规则id，唯一
          uri: lb://byapi-auth # 目标服务，lb为负载均衡
          predicates: # 路由规则
            - Path=/auth/** # 以路径作为判断规则
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: base # 路由规则id，唯一
          uri: lb://byapi-base # 目标服务，lb为负载均衡
          predicates: # 路由规则
            - Path=/base/** # 以路径作为判断规则
          filters:
            - RewritePath=/base/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: byapi-auth
        service-name: byapi-auth
        url: /auth/v3/api-docs
      - name: byapi-base
        service-name: byapi-base
        url: /base/v3/api-docs
